#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p apt-lan
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p apt-lan  || true
fi

# End automatically added section

# Ensure that apt-lan cache is initially populated.
/usr/bin/apt-lan --server-sync
