#!/bin/bash
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p apt-lan
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p apt-lan  || true
fi

# End automatically added section

# Ensure that APT source file exists.
RELEASE=$(grep UBUNTU_CODENAME /etc/os-release | cut -d'=' -f2)
ARCH='amd64'
if [[ $(uname -p) == 'i386' ]]; then
	ARCH='i386'
fi
list_file="/etc/apt/sources.list.d/apt-lan.list"
if ! [[ -e "$list_file" ]]; then
	line="deb [trusted=yes] file:/var/cache/apt-lan/ ${RELEASE}/binary-${ARCH}/"
	echo "$line" > "$list_file"
fi

# Ensure that apt-lan cache is initially populated.
/usr/bin/apt-lan --server-sync
